buildDocker:
  stage: build
  tags:
    - jyaa
  only:
    - main
  script:
    - echo "Construimos la imagen de Docker"
    - docker buildx build . -t grupo8-docker

detenemosContainer:
  stage: test
  tags:
    - jyaa
  needs:
    - buildDocker
  only:
    - main
  script:
    - echo "Detenemos cualqueir tipo de contenedor existente previo"
    - docker stop grupo8 || true

eliminamosContainer:
  stage: test
  tags:
    - jyaa
  only:
    - main
  needs:
    - detenemosContainer
  script:
    - echo "Eliminamos cualqueir tipo de contenedor existente previo"
    - docker rm grupo8 || true

deploy1:
  stage: deploy
  tags:
    - jyaa
  needs:
    - eliminamosContainer
  only:
    - main
  script:
    - echo "Deploy del nuevo contenedor con los cambios"
    - docker run --network javaproyec_jyaa-network -p 8088:8080 -l "traefik.enable=true" -l "traefik.http.routers.grupo8.rule=Host(\`grupo8.jyaa-ci.linti.unlp.edu.ar\`)" -l "traefik.http.routers.grupo8.entrypoints=websecure" -l "traefik.http.routers.grupo8.tls.certresolver=le" -l "traefik.http.services.grupo8.loadbalancer.server.port=8080" -d --name grupo8 grupo8-docker
